version: "3.5"

services:
  elasticsearch:
    image: lenic/elasticsearch-oss:6.2.4
    environment:
      - ELASTICSEARCH_USERNAME=admin
      - ELASTICSEARCH_PASSWORD=admin@123
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
      - target: 9300
        published: 9300
        protocol: tcp
        mode: host
    # volumes:
    # - ./elasticsearch/data:/usr/share/elasticsearch/data:rw

  kibana:
    image: lenic/kibana-oss:6.2.4
    ports:
      - target: 5601
        published: 5601
        protocol: tcp
        mode: host
    depends_on:
      - elasticsearch

  logstash:
    image: lenic/logstash-oss:6.2.4
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host
    depends_on:
      - elasticsearch
    volumes:
      - ./yaml/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
